package:
  name: microscopes-kernels
  version: "0.1.0"

source:
  git_url: https://github.com/datamicroscopes/kernels.git

requirements:
  build:
    - cmake
    - python
    - numpy ==1.8.2
    - cython >=0.20.2
    - distributions >=2.0.23
    - libprotobuf
    - eigen3
    - microscopes-common

  run:
    - python
    - numpy ==1.8.2
    - scipy
    - distributions >=2.0.23
    - libprotobuf
    - protobuf
    - microscopes-common

test:
  imports:
    - microscopes.kernels
    - microscopes.kernels.gibbs
    - microscopes.kernels.slice

about:
  home: https://github.com/datamicroscopes/kernels
