package:
  name: microscopes-kernels
  version: "0.1.0"

source:
  git_url: git@github.com:datamicroscopes/kernels.git

requirements:
  build:
    - cmake
    - python
    - numpy
    - cython 0.20.2
    - distributions
    - microscopes-common
    - microscopes-mixturemodel
    - libprotobuf
  run:
    - python
    - numpy
    - scipy
    - distributions
    - microscopes-common
    - microscopes-mixturemodel
    - libprotobuf
    - protobuf

test:
  imports:
    - microscopes.py.kernels
    - microscopes.cxx.kernels

about:
  home: https://github.com/datamicroscopes/kernels
