package:
  name: microscopes-kernels
  version: "0.1.0"

source:
  git_url: https://github.com/datamicroscopes/kernels.git

requirements:
  build:
    - cmake
    - python
    - numpy
    - cython 0.20.2
    - distributions
    - libprotobuf
    - eigen3
    - microscopes-common
  run:
    - python
    - numpy
    - scipy
    - distributions
    - libprotobuf
    - protobuf
    - microscopes-common

test:
  imports:
    - microscopes.kernels

about:
  home: https://github.com/datamicroscopes/kernels
